# Generated by Django 5.0 on 2024-01-17 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studnet',
            new_name='student',
        ),
    ]
